apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unpatched-vcluster
  namespace: argocd
  labels:
    app.cnoe.io/name: vcluster
spec:
  project: default
  source:
    chart: vcluster
    repoURL: https://charts.loft.sh
    targetRevision: 0.20.0
    helm:
      valuesObject:
        controlPlane:
          proxy:
            extraSANs:
            - unpatched-vcluster-hostname.cnoe.localtest.me
          statefulSet:
            scheduling:
              podManagementPolicy: OrderedReady
        exportKubeConfig:
          server: https://unpatched-vcluster-hostname.cnoe.localtest.me:443
  destination:
    server: https://kubernetes.default.svc
    namespace: unpatched-vcluster
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true