apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-vcluster
  namespace: argocd
spec:
  project: default
  source:
    chart: vcluster
    repoURL: https://charts.loft.sh
    targetRevision: 0.20.0
    helm:
      releaseName: my-vcluster
      valuesObject:
        controlPlane:
          proxy:
            extraSANs:
            - my-vcluster.cnoe.localtest.me
          statefulSet:
            scheduling:
              podManagementPolicy: OrderedReady
        exportKubeConfig:
          server: https://my-vcluster.cnoe.localtest.me:443
  destination:
    server: https://kubernetes.default.svc
    namespace: vcluster-dev
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true