apiVersion: v1
kind: Service
metadata:
  name: kcp-front-proxy-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: front-proxy
    app.kubernetes.io/instance: kcp
    app.kubernetes.io/name: kcp
  ports:
  - name: kcp-front-proxy
    port: 8443
    protocol: TCP
    targetPort: 8443
    nodePort: 30007