apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-frontend
spec:
  selector:
    matchLabels:
      app: podtato-head-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head-frontend
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
        - env:
            - name: PODTATO_COMPONENT
              value: frontend
          name: podtato-head-frontend
          image: ghcr.io/podtato-head/podtato-server:v0.3.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-hat
spec:
  selector:
    matchLabels:
      app: podtato-head-hat
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head-hat
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.1
    spec:
      containers:
        - env:
            - name: PODTATO_COMPONENT
              value: hat
          name: podtato-head-hat
          image: ghcr.io/podtato-head/podtato-server:v0.3.1