apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keptn-podtatohead-deploy
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          workload-class: "app-runtime"
  template:
    metadata:
      name: keptn-podtatohead-{{index .metadata.labels "environment-name"}}
      namespace: argocd
    spec:
      destination:
        server: '{{.server}}'
        namespace: keptn-podtatohead
      source:
        repoURL: cnoe://../../
        targetRevision: HEAD
        # with path set to '.' and cnoe://manifests. we are wanting ArgoCD to sync from the ./manifests directory.
        path: workloads/keptn-podtatohead/stages/{{index .metadata.labels "environment-name"}}
      project: default
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true