apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcp
  namespace: argocd
spec:
  project: default
  source:
    chart: kcp
    repoURL: https://kcp-dev.github.io/helm-charts
    targetRevision: 0.8.0
    helm:
      releaseName: kcp
      valuesObject:
        externalHostname: kcp.cnoe.localtest.me
        kcpFrontProxy:
          ingress:
            enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true